### ISSUE TITLE
Update to vs2017

### ISSUE THREAD

**Issue by dadhi** [drewnoakes/il-visualizer#1]
Not sure what should be done from implementation standpoint. 
But if everything is working as-is with vs15, then readme may state it somewhere.
What do you think?
I need the tool for https://github.com/dadhi/FastExpressionCompiler

**Comment by dadhi** [comment]
OK, I went ahead and updated [my fork](https://github.com/dadhi/il-visualizer) to VS 2017. Works great! Thanks for your work.

**Comment by drewnoakes** [comment]
I'm interested in supporting 2017. Will take a look at the changes you had to make. Do you think it will still work in 2015 with those changes?

FastExpressionCompiler looks very cool too. Will check it out.

**Comment by dadhi** [comment]
Changes are minimal, just dll and .net version update. May be latter was not needed :) Suppose it won't work in vs 2015 due MS.VS.DV dll.

I just wanted it very quick to check some issues in FEC. So thanks again for minimizing my efforts!

**Comment by drewnoakes** [comment]
Thanks. I'll put a release together with binaries for VS2017.

Credit is due to Haibo Luo who wrote the original tool. I've just made it available on GitHub and tidied it up a little bit. Thanks for bringing it forwards.
